module.exports = {
    CANCEL_AND_GO_BACK: '取消並且返回',
    UPLOAD_ARTICLE_COVER: '上傳文章封面',
    ARTICLE_TITLE: '文章標題',
    ARTICLE_CONTENT: '文章內容',
    PREV: '上一頁',
    NEXT: '下一頁',
    REMEMBER_ME: '保持登入',
    EMAIL_ADDRESS: '電子郵件',
    USER_NAME: '使用者名稱',
    PASSWORD: '密碼',
    FORGET_PASSWORD: '忘記密碼?',
    DONT_HAVE_ACCOUNT_SIGN_IN: '沒有帳號？前往註冊帳號',
    SIGN_IN_WITH_EMAIL: '使用 Email 登入',
    SIGN_IN_WITH_USERNAME: '使用帳號登入',
    SIGN_IN_WITH_FACEBOOK: '使用 Facebook 登入',
    SIGN_UP_WITH_EMAIL: '使用 Email 註冊',
    SIGN_UP_WITH_FACEBOOK: '使用 Facebook 註冊',
    SIGN_IN: '登入帳號',
    SIGN_UP: '註冊帳號',
    FIRST_NAME: '名',
    LAST_NAME: '姓',
    ALREADY_HAVE_ACCOUNT_SIGN_IN: '已經有帳號？前往登入',
    COMMENT: '留言',
    PUBLISH: '發佈',
    CANCEL: '取消',
    OK: '好',
    DISCOVER_MORE: '想要看更多嗎?',
    WELCOME_SIGN_IN: '歡迎光臨，請登入進行更多互動哦！',
    ADDED_TO_BOOKMARK: '已加入此收藏',
    REMOVED_FROM_BOOKMARK: '已刪除此收藏',
    UPDATE_ARTICLE_SUCCESS: '已更新文章',
    CREATE_ARTICLE_SUCCESS: '已新增文章',
    ARTICLE_WILL_BE_PUBLISH_TO: '文章將被發佈到',
    DISCUSSION_BOARD: '討論區',
    GO_TO: '前往',
    BRAND_NAME: '傑登遊戲'

}